---
- name: Install Erlang Solutions PGP key
  apt_key:
    url: http://packages.erlang-solutions.com/ubuntu/erlang_solutions.asc
    state: present

- name: Add Erlang Solutions repository
  apt_repository:
    repo: 'deb http://packages.erlang-solutions.com/ubuntu {{ ansible_distribution_release|lower }} contrib'
    state: present

- name: Install Erlang packages
  apt:
    name: esl-erlang
    state: present
    update_cache: yes

- name: Ensure python-software-properties is installed
  apt:
    pkg: python3-software-properties
    state: present


- name: Add trusted key
  apt_key:
    url: https://www.rabbitmq.com/rabbitmq-release-signing-key.asc
    state: present

- name: Add rabbitmq official apt repository
  apt_repository:
    repo: 'deb https://dl.bintray.com/rabbitmq/debian {{ ansible_distribution_release }} main'
    state: present


- name: Install package
  apt:
    name: rabbitmq-server
    update_cache: yes
    state: present

- name: Enable rabbitmq plugins
  rabbitmq_plugin:
    names: rabbitmq_management,rabbitmq_tracing,rabbitmq_federation
    state: enabled
  notify: Restart rabbitmq

- name: Add user
  rabbitmq_user:
    user: "{{ rabbitmq_user }}"
    password: "{{ rabbitmq_pass }}"
    tags: "administrator,{{ rabbitmq_user }}"
    vhost: /
    configure_priv: .*
    write_priv: .*
    read_priv: .*
    state: present

- name: Remove default guest user
  rabbitmq_user:
    user: guest
    state: absent

- name: Ensure vhost /test is present
  rabbitmq_vhost:
    name: /test
    state: present
