---

- name: Install Prerequisites
  apt:
    name: ["gnupg2", "curl", "wget", "apt-transport-https", "software-properties-common"]
    state: latest



- name: Add RabbitMQ repository signing key
  apt_key:
    url: https://dl.cloudsmith.io/public/rabbitmq/rabbitmq-erlang/gpg.E495BB49CC4BBE5B.key
    state: present

- name: Add RabbitMQ repository
  apt_repository:
    repo: https://dl.cloudsmith.io/public/rabbitmq/rabbitmq-erlang/deb/ubuntu bionic main hardy partner
    state: present



- name: Install RabbitMQ Server
  apt:
    name: rabbitmq-server
    state: latest

- name: Enable Web Admin Plugin
  shell:
    cmd: rabbitmq-plugins enable rabbitmq_management
